### ISSUE TITLE
LFR Parsing Failed

### ISSUE THREAD

**Issue by mzw23** [CIDARLAB/Neptune-iGEM-2016#51]
Following error given:
```
POST /api/writeToFile 200 4.339 ms - 46
Exception in thread "main" 
java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException


	at java.lang.Class.getDeclaredMethods0(Native Method)

	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)

	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)

	at java.lang.Class.getMethod0(Class.java:3010)
	at java.lang.Class.getMethod(Class.java:1776)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

child process exited with code 1
POST /api/translateLFR 200 399.233 ms - 28
```

Using LFR design as test:
```
module HemoMixer(finput fi1, fi2, fi3, cinput ci1, ci2, ci3, foutput fo1);
	fchannel fc1, fc2, fc3, fc4, fc5, fc6;
	assign fc1 = fi1 - ci1;
	assign fc2 = fi2 - ci2;
	assign fc3 = fi3 - ci3;
	assign fc4 = fc1 + fc2;
	assign fc5 = fc4 ~;
	assign fc6 = fc5 + fc3;
	assign fo1 = fc6 ~;
endmodule
```

**Comment by aonanam** [comment]
I've been looking into this. Got it to translate to MINT but couldn't Place and Route using muShroomMapper dev standalone using DebugMain (see second option [here](https://github.com/CIDARLAB/MuShroomMapper/wiki/MM-Standalone-Utilization)). This is the closest iteration it got with PaR:
![image](https://cloud.githubusercontent.com/assets/6097214/25357775/1c4c86ec-290d-11e7-9cfd-b8a64849a04b.png). This eps looks good but it's possible that spacing in the .ini is causing PAR to call this a fail.

Tested the file on Neptune Master branch, and couldn't get it to translate as well.

In any case, here are the files I used for the run on standalone dev using DebugMain, and their outputs (in PaR outputs number 7 is the eps I posted above [the best PaR run]):

[HemoRun.zip](https://github.com/CIDARLAB/Neptune/files/953118/HemoRun.zip)

Will look into further soon. My guess is some changes to the .ini would do the trick using MM standalone. Still have to investigate Neptune error, but an update to the MM jar might fix this.
