### ISSUE TITLE
NPE For Mux

### ISSUE THREAD

**Issue by erschwartz** [CIDARLAB/Neptune-iGEM-2016#52]
Device mint:

```V MUX ourDevice 1 to 6 spacing=50 flowChannelWidth=100 controlChannelWidth=100;```

Console log:

```
Processing Device in DesignTree: net_test

true

Beginning Place and Route
PAR iteration 1

Initial Place

Initial Temp

Initial Temp = NaN

Final Temp = NaN
Placement Complete

Time Elapsed: 0:0:0.026557462


flow

0
Routing Complete
Time Elapsed: 0:0:0.003510399


Document is closed

2
------------------------------------------------------------
Device MinX:2147483647

Device MinY:2147483647
Device MaxX:0
Device MaxY:0
------------------------------------------------------------

Document is closed

deviceWidth = 4020
deviceLength = 4020
tileX = 17
tileY = 17
actual Width = 68340.0
actual length = 68340.0

Document is closed

Exception in thread "main" 
java.lang.NullPointerException

	at org.cidarlab.fluigi.output.SVG.drawLayer(SVG.java:222)

	at org.cidarlab.fluigi.output.SVG.drawCellLayer(SVG.java:188)
	at org.cidarlab.fluigi.output.SVG.drawDeviceSVG(SVG.java:80)

	at org.cidarlab.fluigi.fluigi.Fluigi.drawDesignTree(Fluigi.java:354)
	at org.cidarlab.fluigi.fluigi.Fluigi.main(Fluigi.java:260)
```

**Comment by aonanam** [comment]
@rkrishnasanka may be able to help more, but did you follow this format?

[https://github.com/CIDARLAB/mint/wiki/Netlist-Rules-and-Examples](https://github.com/CIDARLAB/mint/wiki/Netlist-Rules-and-Examples)

The DEVICE and two LAYER lines are required, I believe.

**Comment by erschwartz** [comment]
using mint:

```
DEVICE net_test

LAYER FLOW
V MUX ourDevice 1 to 6 spacing=50 flowChannelWidth=100 controlChannelWidth=100;
END LAYER
```

we get:

```

Mux is only supported in 2D devices

Processing Device in DesignTree: myDevice


true

Beginning Place and Route
PAR iteration 1

Initial Place

Initial Temp

Initial Temp = NaN

Final Temp = NaN
Placement Complete

Time Elapsed: 0:0:0.031095144


cells
0
flow
0
Routing Complete
Time Elapsed: 0:0:0.003594874

Document is closed

2
------------------------------------------------------------
Device MinX:2147483647

Device MinY:2147483647
Device MaxX:0
Device MaxY:0
------------------------------------------------------------

Document is closed


deviceWidth = 4020
deviceLength = 4020
tileX = 17
tileY = 17
actual Width = 68340.0
actual length = 68340.0

Document is closed

Document is closed

child process exited with code 0
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/admin/Desktop/neptune/neptune/test/test/proj.ini'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/Neptune/controllers/compileMint.js:117:33)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:486:12)
```

**Comment by aonanam** [comment]
~~The "document is closed" lines mean you got past Place and Route, which is good. Can you check and see if  there are any output files in the folder you specified output to go to? Or if the output folder exists? It looks like it's having trouble putting the output files somewhere.~~

Edit: Didn't see the top bit. I'm not entirely sure what the issue is, unfortunately. I believe you are making a 2D device, as I know that I generally specify 3DDEVICE instead of DEVICE when I design MINT files. Hopefully @rkrishnasanka will know more.

**Comment by rkrishnasanka** [comment]
It seems like this is a result of inconsistent syntaxes and Neptune Problems. I'll be fixing this post May 18th.
