### ISSUE TITLE
Neptune crashes when compiling Mint code in the Netlist Rules and Examples wiki

### ISSUE THREAD

**Issue by evanbowman** [CIDARLAB/Neptune-iGEM-2016#53]
Error occurred when compiling the mint code from the Netlist Rules and Examples wiki page.

Output log:
```
Workspace Directory does not exist. Createing a new Directory
POST /api/getProjects 200 3.408 ms - 15
POST /api/makeProject 501 0.492 ms - 35
POST /api/getProjects 200 5.577 ms - 15
POST /api/makeProject 200 4.343 ms - 28
GET /dashboard 304 11.793 ms - -
GET /specify 304 11.657 ms - -
a user connected
POST /api/scanFiles 200 1.222 ms - 661
POST /api/getFile 200 1.252 ms - 14
POST /api/getFile 200 0.763 ms - -
POST /api/getFile 200 1.674 ms - -
GET /specify 304 5.899 ms - -
a user connected
POST /api/scanFiles 200 0.944 ms - 661
POST /api/getFile 200 2.408 ms - -
POST /api/getFile 200 1.236 ms - -
POST /api/getFile 200 0.780 ms - -
GET /design 304 6.213 ms - -
GET /design 304 21.341 ms - -
GET /javascripts/uploadBar.js 404 4.200 ms - 37
a user connected
POST /api/scanFiles 200 0.396 ms - 661
POST /api/scanFiles 200 1.003 ms - 661
POST /api/getFile 200 4.357 ms - -
POST /api/getFile 200 2.538 ms - -
POST /api/getFile 200 4.072 ms - -
POST /api/getFile 200 1.787 ms - -
/usr/local/lib/node_modules/Neptune/controllers/compileMint.js:65
        mintREGEX = (results[0]).value;
                                ^

TypeError: Cannot read property 'value' of undefined
    at /usr/local/lib/node_modules/Neptune/controllers/compileMint.js:65:33
    at /usr/local/lib/node_modules/Neptune/node_modules/lineder/lib/lineder.js:61:9
    at tryToString (fs.js:425:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:412:12)
```

**Comment by aonanam** [comment]
Can you post the code you used? Just so there's no confusion. The .uf's files contents would be great.

**Comment by evanbowman** [comment]
```
DEVICE net_test

LAYER FLOW
PORT p1, p2 r=100;
V LONG CELL TRAP ct1 numChambers=10 chamberWidth=100 chamberLength=100 chamberSpacing=50 channelWidth=100;

CHANNEL c1 from p1 3 to ct1 1 w=100;
CHANNEL c2 from ct1 2 to p2 1 w=100;

END LAYER

LAYER CONTROL
PORT p3 r=100;
VALVE v1 on c1 w=300 l=100;
VALVE v2 on c2 w=300 l=100;
NET net1 from p3 1 to v1 4, v2 4 channelWidth=50;
END LAYER
```

**Comment by kestas-bme-ece** [comment]
That looks like a bug in Neptune more than mint. I will take a look into it
when I get a chance!
